// <auto-generated />
namespace LibDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class relacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202301182031263_relacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
